fix OpenStack_2_NodeDriver.detach_volume
Since https://github.com/apache/libcloud/pull/1242 the
OpenStack_2_NodeDriver uses a volume object returned via
volumev2_connection. This object will not contain serverId
but server_id. This PR makes the detach_volume method
compatible with v2 volumes.

Fixes:
```
return connection.detach_volume(volume)
File "/usr/local/venv/project/src/apache-libcloud/libcloud/compute/drivers/openstack.py", line 328, in detach_volume
(attachment['serverId'], attachment['id']),
KeyError: 'serverId'
```